language: r

r:
- 4.0.2

sudo: false

latex: false

warnings_are_errors: false

repos: 
  CRAN: https://cran.rstudio.com
  rforge: http://R-Forge.R-project.org

apt_packages:
  - libgdal-dev
  - libudunits2-dev
  - cargo
  - libpoppler-cpp-dev
  
cache:
  packages
  
git:
  depth: false
 
r_packages:
- ISOweek
- coda
- reshape2
- visNetwork
 
r_github_packages: 
- rensa/ggflags
- rstudio/DT
- r-spatial/sf
- r-spatial/lwgeom

script:
  - Rscript deploy.r

notifications:
  email:
    recipients:
     - energystatistics@gov.scot
    on_success: change # default: change
    on_failure: change # default: always
